language: node_js
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
  - develop
install:
  - npm install -g firebase-tools
script:
  - bash build.sh
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    project: teru2blog
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    project: teru2blog-staging
    on:
      branch: develop
      