language: node_js
node_js:
  - 10.16.0
dist: trusty
sudo: false
cache: yarn
branches:
  only:
  - master
  - develop
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn global add firebase-tools nuxt
  - yarn install
  - nvm install 11.11.0
script:
  - nvm use 11.11.0
  - npm rebuild node-sass
  - yarn build
  - ls -al
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: teru2blog-staging
  on:
    all_branches: true
