language: node_js
node_js:
  - stable
dist: trusty
sudo: false
branches:
  only:
  - master
  - develop
install:
  - yarn global add firebase-tools nuxt
  - yarn install
script:
  - bash build.sh
  - nvm use 8.1.0
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    project: teru2blog
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    project: teru2blog-staging
    on:
      branch: develop
